#!/usr/bin/env bash

export CONTECO_LABEL="backup.external - Conteco"
export CONTECO_DESCRIPTION="Backup of all repositories of the external images of the ContEco ecosystem."

export CONTECO_TYPE="backup"
export CONTECO_NAME="external"
export CONTECO_TAG="20200327"

export CONTECO_BASE="external.bash:5.0.9"
export CONTECO_BUILD="image-base"
